import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Home() {
  const [cursos , setCursos] = useState([
    {id: 1, name: 'Next.js'},
    {id: 2, name: 'React.js'},
    {id: 3, name: 'Node.js'},
    {id: 4, name: 'MongoDB'},
    {id: 5, name: 'Express.js'},
    {id: 6, name: 'JavaScript'},
    {id: 7, name: 'TypeScript'},
    {id: 8, name: 'HTML'},
    {id: 9, name: 'CSS'},
    {id: 10, name: 'Bootstrap'},
    {id: 11, name: 'Materialize'},
    {id: 12, name: 'Material UI'},
    {id: 13, name: 'SASS'},
    {id: 14, name: 'Styled Components'},
  ])

  return (
    <div>
      <Head>
        <title>prueba</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Administracion de colegio</h1>
        <Link href='/'>Cursos</Link>
        <Link href='/alumnos'>Alumnos</Link>
        <Link href='/profesores'>Profesores</Link>

        <h2>Lista de cursos</h2>

        {cursos.map((curso) => (
          <div key={curso.id}>
            <Link href={`/cursos/${curso.id}`}>
              <a>{curso.name}</a>
            </Link>
          </div>
        ))}

      </main>
    </div>
  )
}
